### ISSUE TITLE
[Blocked by Docsearch response] Search only works for headers

### ISSUE THREAD

**Issue by atopal** [web3-storage/docs#62]
The search function on https://docs.web3.storage/ doesn't give any feedback. Clicking into it works, it's enlarged automatically, but no other feedback is given on entering a search term.

**Comment by terichadbourne** [comment]
I believe this is a known issue and setup with Algolia can take place now that we're at the right domain. Is that correct @zebateira?

**Comment by jessicaschilling** [comment]
![image](https://user-images.githubusercontent.com/1507828/127062957-cd281f45-8798-4401-909e-b19727bb1931.png)

The search technically works, but since it's not Algolia (it's OOTB Vuepress search) it only queries H1, H2 and (I believe) H3 content. For a small site, that can give the impression of not working.

We can implement Algolia **if we open-source the repo** - @zebateira has successfully done this in the past - but do note it takes a few days for the Algolia folks to approve a request for an open-source license.

**Comment by terichadbourne** [comment]
@zebateira have you already emailed the Algolia/DocSearch folks or would you like me to take that on while you work on other tasks?

**Comment by zebateira** [comment]
@terichadbourne Just sent the request 👍

**Comment by atopal** [comment]
To be clear, the search was not working at all. There was no action beyond enlarging the text field, but it seems fine now. Let's keep this issue for Algolia Search then :)

**Comment by jessicaschilling** [comment]
@zebateira, what's the plan if Algolia approves while you're away? It's easy enough for someone else on the team to add to the code, since we have other examples in situ - we would just need the token.

**Comment by zebateira** [comment]
ah no worries, I'll keep an eye on my email and forward it 👍

**Comment by jessicaschilling** [comment]
Made another request to the Algolia team to discuss open-source licensing. Email is from me, and will note any reply I receive in this issue.

**Comment by atopal** [comment]
We got a positive response.

**Comment by johnnymatthews** [comment]
We've got an Application ID and API Token now, so we can add this in.
